# Site settings
title: Grimoire Lab - Open Source Software Development Analytics toolkit
email: info@bitergia.com
description: "Grimoire Lab is 100% free, open source Software Development Analytics platform, maintained by Bitergia to build dashboards and reports about Open Source and Inner Source Software development activity"
baseurl: ""
url: "http://grimoire.github.io"
twitter_username: bitergia
github_username:  GrimoireLab

# Build settings
markdown: kramdown
permalink: pretty
