# Site settings
title: Grimoire Lab - OpenSource Development Analytics toolkit
email: info@bitergia.com
description: "Grimoire Lab is 100% OpenSource Software Development Analytics platform, maintained by Bitergia to build dashboards and reports about OpenSource and InnerSource Software development activity"
baseurl: ""
url: "http://grimoire.github.io"
twitter_username: bitergia
github_username:  GrimoireLab

# Build settings
markdown: kramdown
permalink: pretty
