version: '2.2'

services:
    mariadb:
      image: mariadb:11.4
      expose:
        - "3306"
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      healthcheck:
        test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--su=root", "--connect", "--innodb_initialized" ]
        retries: 5

    redis:
      image: redis:7.4
      expose:
        - "6379"
      healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        retries: 5

    grimoirelab_core:
      restart: on-failure:3
      image: grimoirelab/grimoirelab:dev
      environment:
        GRIMOIRELAB_DB_HOST: mariadb
        GRIMOIRELAB_DB_PORT: 3306
        GRIMOIRELAB_DB_DATABASE: core_db
        GRIMOIRELAB_DB_USER: root
        GRIMOIRELAB_DB_PASSWORD: ""
        GRIMOIRELAB_REDIS_HOST: redis
        GRIMOIRELAB_REDIS_PORT: 6379
        GRIMOIRELAB_REDIS_PASSWORD: ""
        GRIMOIRELAB_Q_EVENTIZER_JOBS: grimoirelab_jobs
      expose:
        - "9314"
      volumes:
        - core-static:/core_static/
      depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy
      command: grimoirelab run server

    grimoirelab_core_workers:
      image: grimoirelab/grimoirelab:dev
      environment:
        GRIMOIRELAB_DB_HOST: mariadb
        GRIMOIRELAB_DB_PORT: 3306
        GRIMOIRELAB_DB_DATABASE: core_db
        GRIMOIRELAB_DB_USER: root
        GRIMOIRELAB_DB_PASSWORD: ""
        GRIMOIRELAB_REDIS_HOST: redis
        GRIMOIRELAB_REDIS_PORT: 6379
        GRIMOIRELAB_REDIS_PASSWORD: ""
        GRIMOIRELAB_Q_EVENTIZER_JOBS: grimoirelab_jobs
      depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy
      command: grimoirelab run eventizers --workers 10

    sortinghat:
      restart: on-failure:3
      image: grimoirelab/sortinghat
      environment:
        - SORTINGHAT_SECRET_KEY=secret
        - SORTINGHAT_DB_HOST=mariadb
        - SORTINGHAT_DB_PORT=3306
        - SORTINGHAT_DB_DATABASE=sortinghat_db
        - SORTINGHAT_DB_USER=root
        - SORTINGHAT_DB_PASSWORD=
        - SORTINGHAT_REDIS_HOST=redis
        - SORTINGHAT_REDIS_PASSWORD=
        - SORTINGHAT_SUPERUSER_USERNAME=admin
        - SORTINGHAT_SUPERUSER_PASSWORD=admin
        - SORTINGHAT_ALLOWED_HOST=sortinghat,nginx,localhost,127.0.0.1,[::1]
        - SORTINGHAT_CORS_ALLOWED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
      expose:
        - "9314"
      volumes:
        - sortinghat-static:/opt/venv/lib/python3.9/site-packages/sortinghat/static/
      depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy

    sortinghat_worker:
      image: grimoirelab/sortinghat-worker
      environment:
        - SORTINGHAT_SECRET_KEY=secret
        - SORTINGHAT_DB_HOST=mariadb
        - SORTINGHAT_DB_PORT=3306
        - SORTINGHAT_DB_DATABASE=sortinghat_db
        - SORTINGHAT_DB_USER=root
        - SORTINGHAT_DB_PASSWORD=
        - SORTINGHAT_REDIS_HOST=redis
        - SORTINGHAT_REDIS_PASSWORD=
      depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy

    nginx:
      restart: on-failure:3
      image: nginx:latest
      volumes:
        - ../default-grimoirelab-settings/nginx.conf.template:/etc/nginx/templates/default.conf.template
        - ../default-grimoirelab-settings/uwsgi_params:/etc/nginx/uwsgi_params
        - sortinghat-static:/sortinghat:ro
        - core-static:/grimoirelab_core:ro
      ports:
        - 8000:8000
      depends_on:
        - sortinghat
        - grimoirelab_core
      healthcheck:
        test: "curl -s --head http://localhost:8000/identities/api/ | grep Set-Cookie || exit 1"
        retries: 5

volumes:
  sortinghat-static:
  core-static:
